import type { L10n } from "@/lib/i18n";

export type Category = "fullstack" | "ai" | "mobile" | "legacy" | "cms";

export const categories: { id: Category | "all"; label: L10n }[] = [
  { id: "all", label: { pt: "Todos", en: "All" } },
  { id: "fullstack", label: { pt: "Full-stack", en: "Full-stack" } },
  { id: "ai", label: { pt: "IA", en: "AI" } },
  { id: "mobile", label: { pt: "Mobile", en: "Mobile" } },
  { id: "legacy", label: { pt: "Modernização", en: "Modernization" } },
  { id: "cms", label: { pt: "Sites & CMS", en: "Sites & CMS" } },
];

export type MockupId = "headless" | "catalog" | "cashback" | "management" | "legacy" | "cms";

export type Project = {
  id: string;
  mockup: MockupId;
  categories: Category[];
  title: L10n;
  client: L10n;
  tagline: L10n;
  problem: L10n;
  solution: L10n;
  highlights: L10n[];
  stack: string[];
};

export const projects: Project[] = [
  {
    id: "headless-health",
    mockup: "headless",
    categories: ["fullstack"],
    title: { pt: "Plataforma de saúde headless", en: "Headless healthcare platform" },
    client: { pt: "Empresa de soluções médicas", en: "Medical solutions company" },
    tagline: {
      pt: "Site institucional em Next.js consumindo uma API Laravel, montado a partir de módulos reutilizáveis.",
      en: "Next.js corporate site consuming a Laravel API, assembled from reusable modules.",
    },
    problem: {
      pt: "O cliente precisava de um site rápido, indexável e editável pelo time de marketing, enquanto a agência queria parar de reescrever as mesmas seções (banners, FAQ, depoimentos, timeline) a cada projeto.",
      en: "The client needed a fast, indexable site the marketing team could edit, while the agency wanted to stop rewriting the same sections (banners, FAQ, testimonials, timeline) for every project.",
    },
    solution: {
      pt: "Arquitetura headless: front-end Next.js com ISR/SSR para conteúdo público e CSR só para áreas privadas, API Laravel com autenticação JWT única, Postgres e Redis, tudo em Docker. Cada seção é um pacote versionado com semver, instalado no site como dependência.",
      en: "Headless architecture: a Next.js front-end using ISR/SSR for public content and CSR only for private areas, a Laravel API with a single JWT auth flow, Postgres and Redis, all in Docker. Each section is a semver-versioned package installed as a dependency.",
    },
    highlights: [
      { pt: "Padronização da autenticação em JWT único, removendo o Sanctum", en: "Unified authentication on a single JWT flow, removing Sanctum" },
      { pt: "Banners com vídeo, liberados na Content Security Policy", en: "Video banners, allowed through the Content Security Policy" },
      { pt: "Otimização da entrega de imagens pela API", en: "Optimized image delivery from the API" },
      { pt: "Rework de navegação e rodapé, contadores dinâmicos e depoimentos aleatórios", en: "Reworked nav and footer, dynamic counters and randomized testimonials" },
      { pt: "Fixação de versões dos módulos internos e migração de seeders para o kernel compartilhado", en: "Pinned internal module versions and moved seeders to the shared kernel" },
    ],
    stack: ["Next.js", "React", "TypeScript", "Tailwind", "HeroUI", "Laravel", "JWT", "PostgreSQL", "Redis", "Docker"],
  },
  {
    id: "ai-catalog",
    mockup: "catalog",
    categories: ["ai", "fullstack"],
    title: { pt: "Catálogo industrial com IA", en: "AI-powered industrial catalog" },
    client: { pt: "Fabricante de equipamentos industriais", en: "Industrial equipment manufacturer" },
    tagline: {
      pt: "Do cadastro do produto ao catálogo em PDF pronto para gráfica — com tabelas técnicas extraídas por IA.",
      en: "From product entry to a print-ready PDF catalog — with spec tables extracted by AI.",
    },
    problem: {
      pt: "O catálogo impresso era montado à mão, e as tabelas técnicas de cada produto eram digitadas a partir de imagens de fichas, um processo lento e sujeito a erro.",
      en: "The printed catalog was assembled by hand, and every product's spec table was typed in from datasheet images — slow and error-prone.",
    },
    solution: {
      pt: "Integração com o Google Gemini que lê a imagem complementar do produto e gera a tabela técnica estruturada. Um gerador de PDF (mPDF) monta o catálogo completo, por categoria ou por modelo, com capa, contracapa e QR code.",
      en: "A Google Gemini integration reads the product's supporting image and produces a structured spec table. A PDF generator (mPDF) builds the full catalog, per category or per model, with cover, back cover and QR code.",
    },
    highlights: [
      { pt: "Tabela técnica gerada por IA a partir de imagem", en: "Spec table generated by AI from an image" },
      { pt: "Catálogo em PDF pronto para impressão como livro", en: "Print-ready PDF catalog laid out as a book" },
      { pt: "Diagnóstico visual de espaços em branco e ferramenta para preenchê-los", en: "Visual diagnosis of blank areas and a tool to fill them" },
      { pt: "Pré-visualização de modelo 3D, upload por arrastar e cores do produto em grade", en: "3D model preview, drag-and-drop upload and product colors in a grid" },
      { pt: "Downloads por modelo, categoria ou catálogo completo via QR code", en: "Downloads per model, category or full catalog via QR code" },
    ],
    stack: ["Laravel", "Livewire", "Google Gemini", "mPDF", "MySQL", "JavaScript"],
  },
  {
    id: "cashback-club",
    mockup: "cashback",
    categories: ["mobile", "fullstack"],
    title: { pt: "Clube de compras com cashback", en: "Cashback shopping club" },
    client: { pt: "Rede de benefícios e marketplace", en: "Benefits network and marketplace" },
    tagline: {
      pt: "Marketplace web com áreas de associado e vendedor, mais app mobile com pagamento por QR Code PIX.",
      en: "Web marketplace with member and seller areas, plus a mobile app paying via PIX QR codes.",
    },
    problem: {
      pt: "Associados e lojistas usavam painéis inconsistentes entre si e pouco responsivos, e o clube precisava de uma experiência mobile própria.",
      en: "Members and merchants used inconsistent, barely responsive dashboards, and the club needed its own mobile experience.",
    },
    solution: {
      pt: "Padronização dos menus e painéis de associado e vendedor, revisão de responsividade e de listagens, consentimento de cookies (LGPD) e um app React Native/Expo com leitura de QR Code PIX, biometria e ambientes local/homologação/produção.",
      en: "Standardized member and seller menus and dashboards, a responsiveness and listings overhaul, cookie consent (LGPD) and a React Native/Expo app with PIX QR scanning, biometrics and local/staging/production environments.",
    },
    highlights: [
      { pt: "Menu do associado e do vendedor padronizados, com indicação de contexto", en: "Standardized member and seller menus with context indicators" },
      { pt: "Banner de consentimento de cookies", en: "Cookie consent banner" },
      { pt: "Ordenação e layout de DataTables revisados", en: "Reworked DataTables sorting and layout" },
      { pt: "App com leitura de QR Code PIX (copia e cola) e login biométrico", en: "App with PIX QR code scanning (copy & paste) and biometric login" },
    ],
    stack: ["Laravel", "Tailwind", "DataTables", "React Native", "Expo", "MySQL"],
  },
  {
    id: "agency-management",
    mockup: "management",
    categories: ["fullstack"],
    title: { pt: "Sistema de gestão da agência", en: "Agency management system" },
    client: { pt: "Uso interno", en: "Internal tool" },
    tagline: {
      pt: "Projetos, tarefas, contratos de manutenção e banco de horas de clientes em um só lugar.",
      en: "Projects, tasks, maintenance contracts and client hour banks in one place.",
    },
    problem: {
      pt: "A gestão de horas e contratos de manutenção era difícil de auditar e o dashboard não respondia às perguntas do financeiro e do atendimento.",
      en: "Hours and maintenance contracts were hard to audit, and the dashboard didn't answer the questions finance and account managers asked.",
    },
    solution: {
      pt: "Evolução do sistema em Laravel 10 + React/TypeScript: novo dashboard, logs de projetos e tarefas, histórico, filtros por múltiplos status e campos de contrato de manutenção — iterando diretamente com as áreas usuárias.",
      en: "Evolved the Laravel 10 + React/TypeScript system: a new dashboard, project and task logs, history, multi-status filters and maintenance-contract fields — iterating directly with the business users.",
    },
    highlights: [
      { pt: "Logs e histórico de tarefas e projetos", en: "Task and project logs and history" },
      { pt: "Dashboard, contratos e banco de horas reformulados", en: "Reworked dashboard, contracts and hour bank" },
      { pt: "Filtro por múltiplos status e ordenações consistentes", en: "Multi-status filtering and consistent sorting" },
      { pt: "Correções acompanhadas de testes automatizados", en: "Fixes backed by automated tests" },
    ],
    stack: ["Laravel 10", "React", "TypeScript", "Vite", "Bootstrap", "MySQL"],
  },
  {
    id: "legacy-upgrades",
    mockup: "legacy",
    categories: ["legacy"],
    title: { pt: "Modernização de sistemas legados", en: "Legacy system modernization" },
    client: { pt: "Associação industrial e plataforma institucional", en: "Industry association and corporate platform" },
    tagline: {
      pt: "Upgrades incrementais de Laravel 5.8 → 12 e 7 → 13, sem parar a operação.",
      en: "Incremental upgrades from Laravel 5.8 → 12 and 7 → 13, without stopping operations.",
    },
    problem: {
      pt: "Dois sistemas rodavam em versões de Laravel e PHP sem suporte, com vulnerabilidades conhecidas, dependências mortas e nenhum teste para garantir que um upgrade não quebraria nada.",
      en: "Two systems ran on unsupported Laravel and PHP versions, with known vulnerabilities, dead dependencies and no tests to make sure an upgrade wouldn't break anything.",
    },
    solution: {
      pt: "Primeiro uma suíte de testes smoke/end-to-end como rede de segurança; depois um salto de versão por vez, validando cada fase, modernizando sintaxe de rotas e controllers, trocando real-time facades e removendo código e integrações sem uso.",
      en: "First a smoke/end-to-end test suite as a safety net; then one major version at a time, validating each phase, modernizing routes and controllers, replacing real-time facades and removing unused code and integrations.",
    },
    highlights: [
      { pt: "Laravel 5.8 → 12.62 com PHP 8.4, resolvendo 3 CVEs", en: "Laravel 5.8 → 12.62 on PHP 8.4, fixing 3 CVEs" },
      { pt: "Laravel 7 → 13 em um segundo sistema, fase a fase", en: "Laravel 7 → 13 on a second system, phase by phase" },
      { pt: "Migração do skeleton para Application::configure", en: "Skeleton migrated to Application::configure" },
      { pt: "Remoção de integração de pagamento e rotas mortas", en: "Removed an unused payment integration and dead routes" },
    ],
    stack: ["Laravel 5.8 → 13", "PHP 8.4", "PHPUnit", "Composer", "Vue"],
  },
  {
    id: "modular-cms",
    mockup: "cms",
    categories: ["cms", "fullstack"],
    title: { pt: "CMS modular multi-cliente", en: "Multi-client modular CMS" },
    client: { pt: "Mais de 10 sites de clientes", en: "10+ client websites" },
    tagline: {
      pt: "Uma base Laravel com ~100 módulos que vira site institucional, catálogo ou e-commerce para cada cliente.",
      en: "One Laravel codebase with ~100 modules that becomes a corporate site, catalog or store for each client.",
    },
    problem: {
      pt: "A agência atende clientes muito diferentes — indústria, clínicas, padaria, contabilidade, self-storage — e precisa entregar e manter todos com um time enxuto.",
      en: "The agency serves very different clients — manufacturing, clinics, a bakery, accounting, self-storage — and has to ship and maintain them all with a lean team.",
    },
    solution: {
      pt: "Um admin único em Laravel 9 + Livewire onde cada funcionalidade é um módulo ativável (catálogo, orçamentos, newsletter, galeria, carrossel, modal, onde encontrar…). Atuo no front-end dos sites, criação e ajuste de módulos e correções de envio de e-mail.",
      en: "A single Laravel 9 + Livewire admin where every feature is a toggleable module (catalog, quotes, newsletter, gallery, carousel, modal, store locator…). I work on the sites' front-end, building and adjusting modules and fixing email delivery.",
    },
    highlights: [
      { pt: "Nova navbar e menu mobile em tela cheia para distribuidora industrial", en: "New navbar and full-screen mobile menu for an industrial distributor" },
      { pt: "Busca livre e breadcrumbs no catálogo", en: "Free-text search and breadcrumbs in the catalog" },
      { pt: "Módulo de modal reaproveitado entre vários clientes", en: "Modal module reused across several clients" },
      { pt: "Página 404 dinâmica e correções de envio de e-mail", en: "Dynamic 404 page and email delivery fixes" },
      { pt: "Melhorias de responsividade em sites de varejo e serviços", en: "Responsiveness improvements on retail and service sites" },
    ],
    stack: ["Laravel 9", "Livewire", "Blade", "Laravel Modules", "Summernote", "MySQL"],
  },
];
